version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/fampay-assignment
      - /fampay-assignment/node_modules
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet: